Repository rabbitmq/cluster-operator, pull requests merged in 2020-11, with the labels that each got.

#436 Remove duplicated name prefix
  config/default/base/kustomization.yaml
Labels: bug

#443 Use RabbitMQ management image variant
  api/v1beta1/rabbitmqcluster_types.go
  api/v1beta1/rabbitmqcluster_types_test.go
  bin/kubectl-rabbitmq
  charts/rabbitmq/example-configurations.yaml
  charts/rabbitmq/expected-template-output
  config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml
Labels: enhancement

#448 Add automation to bump kubectl rabbitmq in krew index
  .github/workflows/release.yml
  hack/rabbitmq.yaml
Labels: CI
